### ISSUE TITLE
Crash, ML 10.8.3 Xcode 4.5.2

### ISSUE THREAD

**Issue by zhigang1992** [enriquez/PeepOpen-Xcode-4-Plugin#1]
![screen shot 2013-05-08 at 9 54 25 am](https://f.cloud.github.com/assets/1057756/475209/0d5b1e5a-b783-11e2-8643-fcdf55bc4094.png)

**Comment by zhigang1992** [comment]
https://gist.github.com/zhigang1992/5537676

**Comment by enriquez** [comment]
Do you have a project open?

**Comment by enriquez** [comment]
Try this 1fdcc84c443232e98e0f8d000279984af34b6ac2

**Comment by zhigang1992** [comment]
I had a project opened, and it only crash the first time. then it doesn't do anything. (Before I pulled)...
Same after update.

**Comment by enriquez** [comment]
hmm, I'm stumped. Getting the projectRoot for you seems to be `nil` for some reason.  I'm not sure if I'm doing it right here: https://github.com/enriquez/PeepOpen-Xcode-4-Plugin/blob/master/PeepOpen/PeepOpen.m#L59
